-- MySQL Script generated by MySQL Workbench
-- czw, 19 mar 2020, 15:31:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE SCHEMA IF NOT EXISTS `stats` ;
USE `stats` ;

-- -----------------------------------------------------
-- Table `stats`.`players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stats`.`players` ;

CREATE TABLE IF NOT EXISTS `stats`.`players` (
  `id-player` TINYINT(1) UNSIGNED NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id-player`));


-- -----------------------------------------------------
-- Table `stats`.`stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stats`.`stats` ;

CREATE TABLE IF NOT EXISTS `stats`.`stats` (
  `id-stats` TINYINT(1) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `value` INT(5) NOT NULL,
  `players_id-player` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id-stats`, `players_id-player`),
  INDEX `fk_stats-player_players_idx` (`players_id-player` ASC),
  CONSTRAINT `fk_stats-player_players`
    FOREIGN KEY (`players_id-player`)
    REFERENCES `stats`.`players` (`id-player`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stats`.`weapons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stats`.`weapons` ;

CREATE TABLE IF NOT EXISTS `stats`.`weapons` (
  `id-weapons` INT UNSIGNED NOT NULL,
  `name` VARCHAR(5) NOT NULL,
  `hits` INT(4) NOT NULL,
  `shots` INT(4) NOT NULL,
  `kills` INT(3) NOT NULL,
  `players_id-player` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id-weapons`, `players_id-player`),
  INDEX `fk_weapons_players1_idx` (`players_id-player` ASC),
  CONSTRAINT `fk_weapons_players1`
    FOREIGN KEY (`players_id-player`)
    REFERENCES `stats`.`players` (`id-player`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `stats`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stats`.`items` ;

CREATE TABLE IF NOT EXISTS `stats`.`items` (
  `id-item` TINYINT(1) UNSIGNED NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  `pickups` INT(3) NOT NULL,
  `players_id-player` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id-item`, `players_id-player`),
  INDEX `fk_items_players1_idx` (`players_id-player` ASC),
  CONSTRAINT `fk_items_players1`
    FOREIGN KEY (`players_id-player`)
    REFERENCES `stats`.`players` (`id-player`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `stats`.`powerups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stats`.`powerups` ;

CREATE TABLE IF NOT EXISTS `stats`.`powerups` (
  `id-powerups` TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  `pickups` INT(3) NOT NULL,
  `time` INT(9) NOT NULL,
  `players_id-player` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id-powerups`, `players_id-player`),
  INDEX `fk_powerups_players1_idx` (`players_id-player` ASC),
  CONSTRAINT `fk_powerups_players1`
    FOREIGN KEY (`players_id-player`)
    REFERENCES `stats`.`players` (`id-player`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `stats`.`match`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stats`.`match` ;

CREATE TABLE IF NOT EXISTS `stats`.`match` (
  `id-match` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `datetime` VARCHAR(45) NOT NULL,
  `map` VARCHAR(10) NOT NULL,
  `type` VARCHAR(5) NOT NULL,
  `isTeamGame` TINYINT(1) NOT NULL,
  `duration` DECIMAL(5) NOT NULL,
  PRIMARY KEY (`id-match`));


-- -----------------------------------------------------
-- Table `stats`.`user-matches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stats`.`user-matches` ;

CREATE TABLE IF NOT EXISTS `stats`.`user-matches` (
  `id-user-relactions` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `players_id-player` TINYINT(1) UNSIGNED NOT NULL,
  `match_id-match` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id-user-relactions`, `players_id-player`, `match_id-match`),
  INDEX `fk_user-matches_players1_idx` (`players_id-player` ASC),
  INDEX `fk_user-matches_match1_idx` (`match_id-match` ASC),
  CONSTRAINT `fk_user-matches_players1`
    FOREIGN KEY (`players_id-player`)
    REFERENCES `stats`.`players` (`id-player`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user-matches_match1`
    FOREIGN KEY (`match_id-match`)
    REFERENCES `stats`.`match` (`id-match`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
